
INSERT INTO escola.departamentos VALUES (1, 'EDUCAÇÃO EM SAÚDE');
INSERT INTO escola.departamentos VALUES (2, 'ENFERMAGEM');
INSERT INTO escola.departamentos VALUES (3, 'FARMACIA');
INSERT INTO escola.departamentos VALUES (4, 'FISIOTERAPIA');
INSERT INTO escola.departamentos VALUES (5, 'FONOAUDIOLOGIA');
INSERT INTO escola.departamentos VALUES (6, 'MEDICINA');
INSERT INTO escola.departamentos VALUES (7, 'NUTRIÇÃO');
INSERT INTO escola.departamentos VALUES (8, 'ODONTOLOGIA');
INSERT INTO escola.departamentos VALUES (9, 'TERAPIA OCUPACIONAL');
INSERT INTO escola.departamentos VALUES (10, 'ARQUEOLOGIA');
INSERT INTO escola.departamentos VALUES (11, 'ARQUITETURA E URBANISMO');
INSERT INTO escola.departamentos VALUES (12, 'MUSEOLOGIA');
INSERT INTO escola.departamentos VALUES (13, 'ADMINISTRAÇÃO');
INSERT INTO escola.departamentos VALUES (14, 'BIOCIENCIAS');
INSERT INTO escola.departamentos VALUES (15, 'CIÊNCIAS CONTÁBEIS');
INSERT INTO escola.departamentos VALUES (16, 'EDUCAÇÃO');
INSERT INTO escola.departamentos VALUES (17, 'FÍSICA');
INSERT INTO escola.departamentos VALUES (18, 'GEOGRAFIA');
INSERT INTO escola.departamentos VALUES (19, 'LETRAS');
INSERT INTO escola.departamentos VALUES (20, 'MATEMÁTICA');
INSERT INTO escola.departamentos VALUES (21, 'ENGENHARIA QUÍMICA');
INSERT INTO escola.departamentos VALUES (22, 'LETRAS ESTRANGEIRAS');

COMMIT;

INSERT INTO escola.cursos VALUES (1, 'ADMINISTRAÇÃO', 13);
INSERT INTO escola.cursos VALUES (2, 'ARQUEOLOGIA', 10);
INSERT INTO escola.cursos VALUES (3, 'ENGENHARIA QUÍMICA', 21);
INSERT INTO escola.cursos VALUES (4, 'QUÍMICA INDUSTRIAL', 21);
INSERT INTO escola.cursos VALUES (5, 'FÍSICA', 17);
INSERT INTO escola.cursos VALUES (6, 'ASTRONOMIA', 17);
INSERT INTO escola.cursos VALUES (7, 'FÍSICA: ASTROFÍSICA', 17);
INSERT INTO escola.cursos VALUES (8, 'FÍSICA: FÍSICA MÉDICA', 17);
INSERT INTO escola.cursos VALUES (9, 'MUSEOLOGIA', 12);
INSERT INTO escola.cursos VALUES (10, 'LETRAS', 22);
INSERT INTO escola.cursos VALUES (11, 'LETRAS ESPANHOL', 22);
INSERT INTO escola.cursos VALUES (12, 'LETRAS INGLÊS', 22);
INSERT INTO escola.cursos VALUES (13, 'CIÊNCIAS CONTÁBEIS', 15);
INSERT INTO escola.cursos VALUES (14, 'MATEMÁTICA', 20);

COMMIT;

INSERT INTO escola.disciplinas VALUES (1, 'ADMINISTRACAO DE EMPRESAS DE TURISMO', 60);
INSERT INTO escola.disciplinas VALUES (2, 'ADMINISTRACAO DE MARKETING I', 60);
INSERT INTO escola.disciplinas VALUES (3, 'ADMINISTRACAO DE MARKETING II', 60);
INSERT INTO escola.disciplinas VALUES (4, 'ADMINISTRACAO DE PRODUCAO II', 60);
INSERT INTO escola.disciplinas VALUES (5, 'AGRICULTORES-CERAMISTAS', 60);
INSERT INTO escola.disciplinas VALUES (6, 'AGRICULTORES-CERAMISTAS', 60);
INSERT INTO escola.disciplinas VALUES (7, 'ANALISE DE MATERIAL CERAMICO', 60);
INSERT INTO escola.disciplinas VALUES (8, 'ANALISE DE MATERIAL CERAMICO I', 60);
INSERT INTO escola.disciplinas VALUES (9, 'ANALISE DE MATERIAL CERAMICO II', 60);
INSERT INTO escola.disciplinas VALUES (10, 'ANALISE DE MATERIAL LITICO', 60);
INSERT INTO escola.disciplinas VALUES (11, 'ADITIVOS E COADJUVANTES NA INDUSTRIA DE ALIMENTOS', 60);
INSERT INTO escola.disciplinas VALUES (12, 'ALIMENTOS', 60);
INSERT INTO escola.disciplinas VALUES (13, 'ANALISE DE ALIMENTOS', 60);
INSERT INTO escola.disciplinas VALUES (14, 'ANALISE SENSORIAL DE ALIMENTOS', 60);
INSERT INTO escola.disciplinas VALUES (15, 'BIOENGENHARIA', 60);
INSERT INTO escola.disciplinas VALUES (16, 'BIOQUIMICA INDUSTRIAL', 60);
INSERT INTO escola.disciplinas VALUES (17, 'ANALISE DE SISTEMAS LINEARES', 60);
INSERT INTO escola.disciplinas VALUES (18, 'APLICACOES DE LASERS EM MEDICINA', 60);
INSERT INTO escola.disciplinas VALUES (19, 'APLICAÇÕES DE RADIAÇÕES NÃO IONIZANTES EM MEDICINA', 60);
INSERT INTO escola.disciplinas VALUES (21, 'ASTROBIOLOGIA', 60);
INSERT INTO escola.disciplinas VALUES (22, 'ALGEBRA DE TENSORES', 60);
INSERT INTO escola.disciplinas VALUES (23, 'ALGEBRA I', 60);
INSERT INTO escola.disciplinas VALUES (24, 'ALGEBRA II', 60);
INSERT INTO escola.disciplinas VALUES (25, 'ALGEBRA III', 60);
INSERT INTO escola.disciplinas VALUES (20, 'ALGEBRA LINEAR COMPUTACIONAL', 60);
INSERT INTO escola.disciplinas VALUES (26, 'ALGEBRA VETOR E GEOM ANALITICA', 60);
INSERT INTO escola.disciplinas VALUES (27, 'ANALISE MATEMATICA I', 60);
INSERT INTO escola.disciplinas VALUES (28, 'CRÍTICA LITERÁRIA', 60);
INSERT INTO escola.disciplinas VALUES (29, 'ESTILÍSTICA', 60);
INSERT INTO escola.disciplinas VALUES (30, 'CRÍTICA LITERÁRIA', 60);
INSERT INTO escola.disciplinas VALUES (31, 'FONOLOGIA DA LÍNGUA PORTUGUESA', 60);
INSERT INTO escola.disciplinas VALUES (32, 'FUNDAMENTOS DA LÍNGUA LATINA', 60);
INSERT INTO escola.disciplinas VALUES (33, 'HISTÓRIA DA LÍNGUA PORTUGUESA', 60);
INSERT INTO escola.disciplinas VALUES (34, 'ACAO CULTURAL E EDUCATIVA EM MUSEUS', 60);
INSERT INTO escola.disciplinas VALUES (35, 'AÇÃO CULTURAL E EDUCATIVA NOS MUSEUS I', 60);
INSERT INTO escola.disciplinas VALUES (36, 'ACOES CULTURAIS E EDUCATIVAS EM MUSEUS', 60);
INSERT INTO escola.disciplinas VALUES (37, 'ANALISE DA INFORMACAO', 60);
INSERT INTO escola.disciplinas VALUES (38, 'ANTROPOLOGIA NO BRASIL', 60);
INSERT INTO escola.disciplinas VALUES (39, 'ANTROPOLOGIA NOS MUSEUS', 60);
INSERT INTO escola.disciplinas VALUES (40, 'ANTROPOLOGIA VISUAL', 60);

COMMIT;

INSERT INTO escola.alunos VALUES (1, 'Teste', '2022-06-04', 'N', 6);
INSERT INTO escola.alunos VALUES (2, 'Jorge', '2021-01-04', 'S', 9);
INSERT INTO escola.alunos VALUES (3, 'Pericles', '2017-06-20', 'N', 10);
INSERT INTO escola.alunos VALUES (4, 'Lucas', '2017-06-20', 'S', 10);

COMMIT;

INSERT INTO escola.matriculas VALUES (20171, 1, 21, 7.5, 4, 'T');
INSERT INTO escola.matriculas VALUES (20182, 2, 39, 9.3, 26, 'T');
INSERT INTO escola.matriculas VALUES (20221, 3, 28, 4.5, 0, 'T');
INSERT INTO escola.matriculas VALUES (20222, 4, 18, 6.5, 0, 'T');